###

@companyId = 11111111-1111-1111-1111-111111111111
@templateId = ADICIONAR_ID_DO_TEMPLATE_AQUI
@versionId = ADICIONAR_ID_DA_VERSAO_AQUI

###

### Health check
GET http://localhost:3000/health
Accept: application/json
company-id: {{companyId}}

###

GET http://localhost:3000/health/ready
Accept: application/json
company-id: {{companyId}}

###

### Create Template
POST http://localhost:3000/templates
Content-Type: application/json
company-id: {{companyId}}

{
  "name": "Aprovação de usuario",
  "description": "Template para aprovação"
}

###

### List Templates
GET http://localhost:3000/templates
company-id: {{companyId}}

###

### Get Template by ID
GET http://localhost:3000/templates/{{templateId}}
company-id: {{companyId}}

###

### Create New Version
POST http://localhost:3000/templates/{{templateId}}/versions
Content-Type: application/json
company-id: {{companyId}}

{}

###

### Publish Version
POST http://localhost:3000/templates/{{templateId}}/versions/{{versionId}}/publish
company-id: {{companyId}}
